name: Deploy Automático

on:
  push:
    branches:
      - main  # ou a branch principal que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ${{ secrets.PROJECT_PATH }}

            git pull origin main

            npm install

            npm run build || true

            pm2 restart ${{ secrets.APP_NAME }} || pm2 start npm --name "${{ secrets.APP_NAME }}" -- start
